### ISSUE TITLE
Description link is broken

### ISSUE THREAD

**Issue by cagataycali** [guilhermerodz/luna#3]
I wanted to visit website in description but looks like the link is broken :/ Huge congrats 🎉🎉

**Comment by HaidarEzio** [comment]
yeah same from my side

**Comment by guilhermerodz** [comment]
hi @cagataycali @HaidarEzio 

oh, we're still shaping the development/DX at the moment, so the website isn't a priority.

to solve the confusion, I've now removed the website link of the Github project until we finally have a landing page!

**Comment by HaidarEzio** [comment]
Nice, super excited for the final result !
